 Full Working Setup for MetalLB on KinD
🔧 Step 1: Install MetalLB

kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.10/config/manifests/metallb-native.yaml
 Step 2: Get KinD Network Subnet

docker network inspect kind | grep Subnet


 Step 3: Create MetalLB Config (save as metallb-config.yaml)

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.18.255.200-172.18.255.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2adv
  namespace: metallb-system

kubectl apply -f metallb-config.yaml
