apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wev-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
    containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: site-data
    volumes:
    - name: site-data
      persistentVolumeClaim:
        claimName:  web-pvc