apiVersion: v1
kind: Pod
metadata:
  labels:
    name: redis
  name: redis
spec:
  containers:
    - name: redis
      image: redis:5.0.4
      
      volumeMounts:
        - mountPath: "/data/redis"
          name: "redis-storage"
  volumes:
    - name: "redis-storage"