---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  APP_ENV: production
  APP_DEBUG: "false"
  APP_VERSION: "1.2.3"
---
apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
  - name: app-container
    image: busybox
    command: [ "sh", "-c", "env; sleep 3600" ]
    envFrom:
    - configMapRef:
        name: my-config
