apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
    - name: app
      command: ["/bin/sh", "-c", "sleep","2500"]
      image: busybox:
      envFrom:
        - configMapRef:
            name: demo-config